const words = [
  "bzmxvzjxfddcuznspdcbwiojiqf",
  "mwguoaskvramwgiweogzulcinycosovozppl",
  "uigevazgbrddbcsvrvnngfrvkhmqszjicpieahs",
  "uivcdsboxnraqpokjzaayedf",
  "yalc",
  "bbhlbmpskgxmxosft",
  "vigplemkoni",
  "krdrlctodtmprpxwditvcps",
  "gqjwokkskrb",
  "bslxxpabivbvzkozzvdaykaatzrpe",
  "qwhzcwkchluwdnqjwhabroyyxbtsrsxqjnfpadi",
  "siqbezhkohmgbenbkikcxmvz",
  "ddmaireeouzcvffkcohxus",
  "kjzguljbwsxlrd",
  "gqzuqcljvcpmoqlnrxvzqwoyas",
  "vadguvpsubcwbfbaviedr",
  "nxnorutztxfnpvmukpwuraen",
  "imgvujjeygsiymdxp",
  "rdzkpk",
  "cuap",
  "qcojjumwp",
  "pyqzshwykhtyzdwzakjejqyxbganow",
  "cvxuskhcloxykcu",
  "ul",
  "axzscbjajazvbxffrydajapweci",
];

const queries = [
  [4, 4],
  [6, 17],
  [10, 17],
  [9, 18],
  [17, 22],
  [5, 23],
  [2, 5],
  [17, 21],
  [5, 17],
  [4, 8],
  [7, 17],
  [16, 19],
  [7, 12],
  [9, 20],
  [13, 23],
  [1, 5],
  [19, 19],
];

export default [words, queries] as [string[], number[][]];
